import fs from 'node:fs/promises';import path from 'node:path';import {SpreadsheetFile,Workbook} from '@oai/artifact-tool';
const root='/Users/xiaoyu/Documents/ale/repairs/build/2784-current',task=path.join(root,'task'),renders=path.join(root,'workbook-renders');await fs.mkdir(renders,{recursive:true});const head={fill:'#415B76',font:{bold:true,color:'#FFFFFF'},wrapText:true},body={wrapText:true,verticalAlignment:'top',borders:{bottom:{style:'thin',color:'#D9E0E7'}}};
function add(b,n,rows,w){const s=b.worksheets.add(n),r=s.getRangeByIndexes(0,0,rows.length,w.length);r.values=rows;r.format=body;s.getRangeByIndexes(0,0,1,w.length).format=head;w.forEach((x,i)=>s.getRangeByIndexes(0,i,rows.length,1).format.columnWidth=x);r.format.autofitRows();s.freezePanes.freezeRows(1);s.showGridLines=false;}
async function finish(b,l,f){for(const s of b.worksheets.items){const p=await b.render({sheetName:s.name,autoCrop:'all',scale:1.2,format:'png'});await fs.writeFile(path.join(renders,`${l}-${s.name}.png`),new Uint8Array(await p.arrayBuffer()));}const e=await b.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A',options:{useRegex:true,maxResults:100},maxChars:5000});await fs.writeFile(path.join(renders,`${l}.errors.ndjson`),e.ndjson,'utf8');const i=await b.inspect({kind:'sheet,table',include:'id,name,values',tableMaxRows:100,tableMaxCols:8,maxChars:45000});await fs.writeFile(path.join(task,`${f}.inspect.ndjson`),i.ndjson,'utf8');const out=await SpreadsheetFile.exportXlsx(b);await out.save(path.join(task,f));}
const a=Workbook.create();
add(a,'交付物答案清单',[
 ['交付物名称','固定路径/命名规则','用途','判定方式'],['Helm Chart','output/chart/tenant-dashboards','生成租户仪表盘ConfigMap','helm lint和helm template'],['开发环境values','output/values/development.yaml','保存开发环境结构化配置','YAML字段核对'],['生产环境values','output/values/production.yaml','保存生产环境结构化配置','YAML字段核对'],['开发候选清单','output/renders/development.yaml','供观测团队核对开发对象','结构化对象比较'],['生产候选清单','output/renders/production.yaml','供观测团队核对生产对象','结构化对象比较'],['仪表盘对象清单','output/reports/dashboard_inventory.csv','列出标题与查询','按环境和租户比较'],['字段迁移表','output/reports/migration_map.csv','记录源字段与目标字段','按tenant_id比较'],['本地构建入口','output/tools/build_delivery.py','从业务材料生成交付','在Windows11空目录运行'],['发布说明','output/RELEASE-NOTES.md','记录岗位接续与现场边界','与候选材料互证'],['结果说明','output/README.txt','说明各目录用途','与实际路径互证']],[34,82,72,64]);
add(a,'固定字段答案',[
 ['交付物或对象','字段路径','正确值','来源与验证'],['迁移表','tenant_text_executed','false','migration_map.csv'],['开发环境','environment.label','development','environment_values.csv'],['开发环境','environment.cluster','edge-dev','environment_values.csv'],['生产环境','environment.label','production','environment_values.csv'],['生产环境','environment.cluster','edge-prod','environment_values.csv'],['Chart','values字段','tenantId、displayName、metricName、window','migration_policy.json']],[40,52,74,66]);
add(a,'固定集合答案',[
 ['交付物或对象','字段或集合','正确集合','判定方式'],['环境','environment','development、production','集合精确匹配'],['租户','tenant_id','alpha、beta','集合精确匹配'],['指标策略','allowed_metrics','http_requests_total、request_duration_seconds_count','migration_policy.json'],['窗口策略','allowed_windows','5m、10m、15m','migration_policy.json'],['对象','ConfigMap名称','alpha-dashboard、beta-dashboard','按每个环境比较'],['禁止字段','forbidden_value_fields','titleFragment、queryFragment','迁移策略与输出搜索']],[40,48,108,68]);
add(a,'固定数值答案',[
 ['交付物或对象','字段或位置','正确值','容差','来源与验证'],['候选清单','环境数',2,0,'environment_values.csv'],['候选清单','每环境ConfigMap数',2,0,'tenant_catalog.csv'],['对象清单','记录数',4,0,'环境与租户组合'],['迁移表','记录数',2,0,'tenant_catalog.csv'],['交付Chart','tpl调用数',0,0,'模板文本搜索'],['双环境values','片段字段数',0,0,'YAML字段检查']],[40,48,36,24,72]);
add(a,'允许变体答案',[
 ['对象','允许变化','不可变化','判定方式'],['Chart组织','辅助模板与文件拆分可以变化','不执行租户文本且结构化字段受约束','Helm检查与模板搜索'],['YAML','键序、缩进与外层引号可以变化','解析后的对象、标题和查询不能变化','结构化解析比较'],['CSV报告','行序可以变化','表头、复合业务键和值不能变化','按业务键排序比较'],['说明材料','措辞和段落可以变化','材料用途、团队职责和现场边界不能写错','与实际交付互证']],[34,82,98,66]);await finish(a,'关键标准答案','关键标准答案.xlsx');
const s=Workbook.create();add(s,'任务规格',[
 ['模块','规格内容'],['任务ID','tenant_dashboard_text_migration'],['主软件','Helm'],['辅助工具','PowerShell7、Python3.12、UTF-8文本编辑器、CSV查看器和JSON查看器'],['输入来源','可观测平台版本组提供的租户目录、环境值、迁移策略、变更说明和旧Chart'],['输入获取方式','从交接压缩包解压到Windows11本地目录'],['原始输入文件','tenant_catalog.csv、environment_values.csv、migration_policy.json、change_request.md、starter和README.txt'],['目标输出文件','output/chart、output/values、output/renders、output/reports、output/tools、output/RELEASE-NOTES.md和output/README.txt'],['核心操作链','核对旧入口→建立结构化租户字段→约束values→改写ConfigMap模板→双环境Helm检查与渲染→整理对象清单和迁移表'],['租户字段','tenantId、displayName、metricName和window来自tenant_catalog.csv，tenantId为对象业务键'],['环境字段','label、cluster、release_name和namespace来自environment_values.csv，两个环境分别形成values和清单'],['内容生成','标题由displayName、策略分隔符和label组成，PromQL由metricName、tenantId、cluster与window生成'],['执行边界','values不接收titleFragment或queryFragment，Chart模板不调用tpl执行租户文本'],['策略边界','metricName与window必须属于migration_policy.json中的集合，其他值停止处理'],['对象闭合','每个环境与租户组合对应一个ConfigMap，对象清单与候选清单逐项一致'],['迁移记录','每个tenant_id有一行源字段到目标字段映射，tenant_text_executed为false'],['岗位接续','观测团队核对对象清单，维护窗值班负责现场应用与仪表盘观察'],['完成条件','新Chart可由Helm检查并生成双环境候选清单，租户片段入口已移除，报告与清单可相互复算'],['可验证点','输入消费者、values字段集合、schema约束、tpl调用数、对象集合、标题与查询、报告业务键和岗位边界'],['不适合作为评分点的内容','编辑器、临时目录、YAML缩进、模板文件拆分、CSV行序、说明排版和具体命令输入方式']],[34,148]);await finish(s,'任务规格转化','任务规格转化.xlsx');
